name: Build and Publish Docker Bot

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          if [[ $REPO_NAME != dockerbot-* ]]; then
            REPO_NAME="dockerbot-$REPO_NAME"
          fi
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$REPO_NAME
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          TAG=latest
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
